### ISSUE TITLE
config::environment.rb

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/ttt-with-ai-project#11]
I went to run my program from the bin file, and I got this error: 

`rescue in require_all': no such file to load -- lib (LoadError)

I looked in the environment.rb file and changed updated it to :

`require_all '../lib'`

It can now find lib by backing-out of the config repo.

**Comment by AnnJohn** [comment]
Hi @onyoo is this still an issue for you? Thanks!

**Comment by onyoo** [comment]
Hi Ann!
Just went back, and it seems to be working with the original code. I clearly remember it not working without the fix before. Sorry for the confusion!

**Comment by AnnJohn** [comment]
Great! And thank you for all your fantastic PRs!
