### ISSUE TITLE
won't show the lab is complete.

### ISSUE THREAD

**Issue by Alvinluipo** [learn-co-curriculum/ttt-with-ai-project#13]
I finished the this lab for ttt-with-ai-project, but it won't mark as being completed.

**Comment by AnnJohn** [comment]
Hi @Alvinluipo, this might be an engineering bug so could you instead file a bug report? If you hover over your profile pic in Learn, you'll see an option to Report a Bug. Also, you can use the Ask a Question tool in Learn and someone from our team will get back to you right away. Thanks!
