### ISSUE TITLE
Review lab and implement better CLI solution

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/ttt-with-ai-project#2]
Someone should review this and solve and I think my CLI technically doesn't meet spec.

cc @AnnJohn

**Comment by jmburges** [comment]
reviewed.

**Comment by AnnJohn** [comment]
fixed

**Comment by pletcher** [comment]
It seems like a solution has been added -- @jmburges @aviflombaum ?

**Comment by pletcher** [comment]
@gj added a new solution that looks pretty solid: https://github.com/learn-co-curriculum/ttt-with-ai-project/pull/25
