### ISSUE TITLE
Issue with Learn IDE

### ISSUE THREAD

**Issue by vanitanaidu** [learn-co-curriculum/ttt-with-ai-project#31]
Hi guys.. I just installed the new version of Learn IDE. Now I have trouble opening more than 2 files in my text editor... I restarted my computer and I installed the program twice.. Nothing seems to work.. Could anyone help me out with this? Thank u

**Comment by bhollan** [comment]
Hi @vanitanaidu !  If this is an issue with the IDE, you should use the Ask A Question feature of learn.co (I know you are, I'm chatting with you right now about it, I'm basically just leaving a note for anyone who reads this in the future).

Keep up the good work!

CC: @aturkewi [ready to close]
