### ISSUE TITLE
`display` method tests not checking for proper alignment

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/ttt-with-ai-project#32]
Encountered student code that renders an instance of `Board` and whose `display` function runs and passes the tests, but is clearly not rendering it properly (see pic in link below).

I'm not sure how to check for a perfectly formed/rendered board, but I think these tests should be modified/appended.

http://www.awesomescreenshot.com/image/1962687/5cf6a20b64e9ce60df9fedbfd2a7e6b6

CC: @aturkewi

**Comment by aturkewi** [comment]
@bhollan I'm gonna say this is alright actually. It's not great that the board is getting rendered in the test (ideally the test should catch that and _not_ display it), but it doesn't mean that it's not rendering properly when the game is played. Closing

If possible, in the future, if you could post the code that created this, that would be really helpful. If it's all in one file, you can drop it in here, or if the student did a `learn save` than link to the specific commit. But there is too much guess work here for me to re-create.

**Comment by bhollan** [comment]
Good call about the code.  Will do for next time.
