### ISSUE TITLE
Missing Open button

### ISSUE THREAD

**Issue by anglinchristina** [learn-co-curriculum/ttt-with-ai-project#38]
This lab does not have a blue open button in my browser.  I've forked the lab on GitHub but when I run $ learn open ttt-with-ai-project-cb-000 on the IDE, I get the message "It looks like this lesson is a Readme. Please open it in your browser."

I'm working locally but is there a way to open this project in Learn IDE?  I'm using the latest version (v2.5.3) and don't have any available updates.  Thanks!

**Comment by gj** [comment]
Hi @anglinchristina !

For the TTT with AI project (and most other projects), you'll have to [manually open the lab](help.learn.co/workflow-tips/github/how-to-manually-open-a-lab).

To clear things up, I added a note to the README: 18827f7

Thanks!
