### ISSUE TITLE
Human player spec

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/ttt-with-ai-project#39]
The human player spec is written in such a way that the 'asks the user for input and returns it' test will fail if you try to use the valid_move? method to validate the move. It will work if line 16 is changed to read "expect(human.move(Board.new)).to eq("1")"

**Comment by DanielSeehausen** [comment]
Thank you for spotting this issue and providing feedback.









Thanks @lizbur10! 

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
