### ISSUE TITLE
Are you expecting them to pull their solution from previous lab?

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/ttt-with-ai-project#4]
Are you expecting them to pull their solution from a previous lab? We should make a comment about what that looks like with pairing, who should they grab etc.

**Comment by jmburges** [comment]
postpone

**Comment by pletcher** [comment]
@jmburges I'm not sure I understand the original comment -- could you elaborate?

**Comment by aturkewi** [comment]
@jmburges I'm going to close this. I'm with Chuck, I'm not sure I understand. I'm going to close this for now, but please feel free to re-open with more info :)
