### ISSUE TITLE
Player_spec test has 2 winning combinations...

### ISSUE THREAD

**Issue by jilustrisimo** [learn-co-curriculum/ttt-with-ai-project#40]
ln. 109 
```
 it 'returns the correct winning combination in the case of a win' do
      game = Game.new
      game.board.cells = ["X", "O", "X",
                          "O", "X", "X",
                          "O", "O", "X"]

      expect(game.won?).to contain_exactly(2, 5, 8)
end
```

This test returns two winning combinations.  If a student defines `[0,4,8]` first in the WINNING_COMBINATIONS const the test will never pass.

**Comment by DanielSeehausen** [comment]
Excellent find @jilustrisimo! Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by amelieoller** [comment]
I believe the test still returns two winning combinations (this time two different ones):

```
game.board.cells = [
  "X", "O", "X",
  "O", "O", "X",
  "O", "O", "X"
]
```

**Comment by kwebster2** [comment]
@DanielSeehausen Looks like there are still two wins
