### ISSUE TITLE
typo- confusing sentence

### ISSUE THREAD

**Issue by ode-to-the-code** [learn-co-curriculum/ttt-with-ai-project#41]
Note on name spacing: You'll notice here that **we do Players::Human < Player does not work because the Players module is not yet defined.**

**Comment by DanielSeehausen** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
