### ISSUE TITLE
Change test order

### ISSUE THREAD

**Issue by joshuabamboo** [learn-co-curriculum/ttt-with-ai-project#43]
`#won?` and `#draw?` are helpers to create the `#over?` method, so it may be helpful for students to build the helpers first. As it is now, the[ tests have you build `#over?`](https://github.com/learn-co-curriculum/ttt-with-ai-project/blob/master/spec/04_game_spec.rb#L78) before [`#won?`](https://github.com/learn-co-curriculum/ttt-with-ai-project/blob/master/spec/04_game_spec.rb#L101) and [`#draw?`](https://github.com/learn-co-curriculum/ttt-with-ai-project/blob/master/spec/04_game_spec.rb#L128). 

I've seen significant confusion from students on this, and it often leads to an infinite loop in their code. 

@cjbrock @ruthmesfun

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#45.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
