### ISSUE TITLE
#won? spec

### ISSUE THREAD

**Issue by rockychiang** [learn-co-curriculum/ttt-with-ai-project#46]
In this lab one of the test for the #won? method is whether the method gives the right array for a won board state. the test expect us to return an array where X has won but the problem is the board state shows us that both X and O has won the game thus breaking this test.

**Comment by curiositypaths** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
