### ISSUE TITLE
Lots of random code getting added in

### ISSUE THREAD

**Issue by ryerayne** [learn-co-curriculum/ttt-with-ai-project#47]
Hello! When I close and reopen this lab, a bunch of random code gets scattered through my code (like "<<<<<<<<<<<<<HEAD" or long random looking strings. Occasionally, a keyword here or there seems to be deleted. It's usually on two or more documents. 

Also, my lab shows all tests passing when I run learn submit, but the checklist on the side won't show that they are passing.

**Comment by sgharms** [comment]
Hi @christianavdm 

This issue is caused by a "marge conflict." So these aren't strictly speaking random code :)

If you still experience this issue please use AAQ to get help resetting your code to a good place.
