### ISSUE TITLE
When I open this lab (partially completed) via the learn IDE it only loads a subset of my "lib" files from Githug

### ISSUE THREAD

**Issue by efkarst** [learn-co-curriculum/ttt-with-ai-project#49]
I have a two files in my "lib" folder (game.rb and players/computer.rb) that never load when I open the learn IDE to continue working on this lab. I have to re-create them every time I work on the lab.

**Comment by sgharms** [comment]
Hi there! This request sounds like it might be a bug in the Learn platform.
[Raising issues on GitHub][raise] should be reserved for problems with the
curriculum itself (doesn't work, throws a Ruby error, etc.)

Our product team loves to hear about our Learners' innovative interface
improvements. You can reach them at support@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try
to discern a proper path to resolution.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
