### ISSUE TITLE
We cover custom errors in the track, but this lab doesn't use them in what would be perfect places!

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/ttt-with-ai-project#5]
What if someone puts in a 15 into position or something like that? I feel like this is a perfect opportunity to teach both defensive coding as well as errors again

**Comment by aviflombaum** [comment]
I don't think the game should raise or rescue an error when someone puts in invalid input for a move. It can do what it is doing - simply ask for valid input. Not sure what you're talking about...but if it's like

raise InvalidInput

and then in turn

```
begin
  input
rescue InvalidInput
  turn
end
```

Thats not good.

I don't see anyplace for a custom error.

**Comment by jmburges** [comment]
so the game should do normal error checking by checking the valid method stuff. Figured it could be a cool But if you are writing the board class, and someone else is writing the game class you want to make sure they don’t give you wrong input kinda deal. Rather defensive code, but something I would do if I was working on a team.

On October 30, 2015 at 10:44:12 AM, Avi Flombaum (notifications@github.com) wrote:

I don't think the game should raise or rescue an error when someone puts in invalid input for a move. It can do what it is doing - simply ask for valid input. Not sure what you're talking about...but if it's like

raise InvalidInput

and then in turn

begin
  input
rescue InvalidInput
  turn
end

Thats not good.
