### ISSUE TITLE
There needs to be an explanation for how to add people to the project and interact with the checklist on the right side of the screen.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/ttt-with-ai-project#50]
Hello. This is the first lab that is designed to be a group project, but neither the README nor the help articles mention how to add someone to your lab, complete the checklist, and submit the lab. 

To be fair, some good information is found here: http://help.learn.co/online-immersive-bootcamps/online-web-developer-program-faqs/group-projects 

However, even that article doesn't show how to interact with the buttons on the right side of the screen (under "Forked this Lab") that are unique to group projects. 

Here's what needs to be mentioned, at least in this lab:

- Select either "Solo" or "Team"
- Find and add a person to the project with the blue "+" button (provided that they have not forked or completed the lab)
- Remove people from the project by clicking the red "-" button on their profile pictures 
- Check off each item in the checklist by clicking the white dots next to them
- Click "Submit" once all items have been checked off.

Thanks for looking into this, as always!

Sdcrouse

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#51.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
