### ISSUE TITLE
Game class question

### ISSUE THREAD

**Issue by sharonrieger** [learn-co-curriculum/ttt-with-ai-project#52]
Hi. I went back to previous labs to see if we were taught the concept that would have helped me with the initialize method in Game class. Couldn't find anything that would have helped me with it. Also, combed over the specs and lab instructions. I feel like there is a step missing that would have prepared me for this initialize method. Did I miss something due to not grasping what was required or was this just kind of snuck in here. I tried all kinds of Google searches too. 
def initialize(player_1 = Players::Human.new("X"), player_2 = Players::Human.new("O"), board = Board.new)
        @board = board
        @player_1 = player_1
        @player_2 = player_2
      end

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #51 .
We're closing this issue but invite you to follow #51
