### ISSUE TITLE
Class Properties

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/ttt-with-ai-project#53]
Class properties have not been taught at this point. Without introducing and teaching the concept prior to this lab, you're setting students up for failure. If I'm incorrect, just point me in the direction of the lesson that teaches this material. 

Best,
Amanda

**Comment by maxwellbenton** [comment]
Thank you for reaching out and providing feedabck @helloamandamurphy,

Just to be clear, when you are referring to class properties, do you mean this paragraph?

> The Board class represents the data and logic of a Tic-tac-toe game board.  It has a property, cells, that stores the data of the state of the board in an array.

A class property, in this case, is referring to a Board instance variable. More info is available from these lessons in the Object Properties section of the learn course (some lessons: https://github.com/learn-co-curriculum/ruby-instance-variables-lab, https://github.com/learn-co-curriculum/ruby-object-attrs-readme, https://github.com/learn-co-curriculum/ruby-object-attributes-lab, https://github.com/learn-co-curriculum/oo-meowing-cat).

If this is not what you meant, please feel free to reopen this ticket. If you need more immediate assistance, please use the Ask a Question feature on learn.co to get help from an online instructor. The lab does have some known issues and will be reworked in an upcoming update.

Thank you for providing feedback!
